### ISSUE TITLE
Show breakdown if we already have data

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/gender-balance#164]
If we already have a source of data for a country, we currently just tell people we don't need them to play. 

We should also show the breakdown by gender for that country. (split from #119)

**Comment by chrismytton** [comment]
We now allow you to play countries that we already have gender data for. I'm closing this ticket in favour of https://github.com/everypolitician/gender-balance/issues/144, which is slightly different in that it's showing *your* votes rather than the official data, but that seems clearer now. Feel free to re-open if you disagree though :)
