### ISSUE TITLE
Show legislature and level info

### ISSUE THREAD

**Issue by lizconlan** [everypolitician/gender-balance#207]
Would be nice (but not essential) if I could see which data set I'm working through

**Comment by tmtmtmtm** [comment]
We took that away, as it used up a lot of screenspace (the names are often quite long), for what didn't seem to be a lot of value. In the general case, when you first start on a country, you'll be on the most recent period for the legislature you've just selected, and at the end of the level it does tell you which period you're progressing to next. 

That requires people to be able to _remember_ that if they stop and start again later, but I'm unsure that that's a significant enough problem. Feel free to persuade me otherwise though (or suggest a way of providing the information somewhere more cleanly)

**Comment by lizconlan** [comment]
@tmtmtmtm probably for the best. Maybe it would make more sense hidden as a tooltip or as part of a future "your progress" screen. Certainly not a must-have for launch (if at all!)
