### ISSUE TITLE
Hard to find the UK?

### ISSUE THREAD

**Issue by MyfanwyNixon** [everypolitician/gender-balance#271]
User comment via tweet:

> I couldn't find United Kingdom in the country search - tried United Kingdom, Britain, Great Britain, finally scrolled - 'UK'

**Comment by andylolz** [comment]
Could implement the `alternative-spellings` thing that http://everypolitician.org uses…

Note that only ‘UK’ and ‘US Virgin Islands’ are abbreviated currently. I don’t know if it would be a pain to change this, though.

**Comment by tmtmtmtm** [comment]
@andylolz The US Virgin islands doesn't seem to be abbreviated to me… Where are you seeing that?

The issue of it not being an alternative spelling on the front of EP itself is a good find — it turns out that you needed to add the dots to "U.S.", but I've fixed that now.

The UK being abbreviated everywhere rather than spelled out is one that's been bugging me for a while, so this has prompted me to fix that. Hopefully that will filter its way to here soon, and then @MyfanwyNixon can let the OP know.

There's also https://github.com/everypolitician/gender-balance/issues/55 for finding a way of adding an alternative spellings thing here.

*phew* :)

**Comment by andylolz** [comment]
> The US Virgin islands doesn't seem to be abbreviated to me… Where are you seeing that?

Well… I mean as opposed to The [United States Virgin Islands](https://en.wikipedia.org/wiki/United_States_Virgin_Islands).

> There's also #55 for finding a way of adding an alternative spellings thing here.

Aha! Great. I might take a look at that one.

**Comment by tmtmtmtm** [comment]
> Well… I mean as opposed to The United States Virgin Islands.

Ah, gotcha. I thought you meant it was coming up as "USVI" or something. I think "US Virgin Islands" is OK — going for the full "United States Virgin Islands" seems equivalent of making the UK be "United Kingdom of Great Britain and Northern Ireland" rather than just "United Kingdom". I'm open to persuasion on this, though.

> Aha! Great. I might take a look at that one.

Excellent!
