### ISSUE TITLE
Undo

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/gender-balance#30]
If I accidentally mis-classify someone, I should be able to undo it.

(Perhaps by showing the last classification somewhere on the screen "You picked [whatever] for [person]" with a way to go back and clear/change that?)

**Comment by zarino** [comment]
Devil's advocate says: no, undo will make people sloppy, if they make a mistake they make a mistake, and it won't typically result in a person being misclassified, because X number of other players would have to make the same mistake.

**Comment by MyfanwyNixon** [comment]
I've just had a go and I wanted *either* an undo button, or an assurance that I could assess my work at the end. My ideal would be both. At the end I'd like to see a display of the two categories and have the chance to drag any I'd mis-tagged to the correct section.

In my case, a mistake happened, as I suspect it frequently will, because I was on a run of about 30 males and clicking 'male' so fast and often that when a woman appeared, I automatically clicked it again.

**Comment by garethrees** [comment]
> I've just had a go and I wanted either an undo button, or an assurance that I could assess my work at the end.

+1 – My mind said "Male" but it was hard to not click the "Female" button when I was already hovered over it.

I'd go with a column for each gender so that you could easily scroll down through the faces at the end

**Comment by MyfanwyNixon** [comment]
+1 via a blog comment: "This is quite cool, but it needs an “undo” button. It’s quite easy to get into the rhythm of clicking “male”, unfortunately."

**Comment by TomSteinberg** [comment]
I've also found this to be needed, and now so has @FOIMonkey

**Comment by FOIMonkey** [comment]
My browser lagged leading to a couple women being marked as men. It was easy to spot when this happened so it would have been good to have a way to at least have flagged it as needing changing.

**Comment by tmtmtmtm** [comment]
I'm actually gradually making peace with the idea that sometimes I simply make mistakes, and that those will be cancelled out by everyone else.

**Comment by andylolz** [comment]
Since switching to keyboard shortcuts, I’ve made several errors that I’ve noticed immediately after pressing the wrong button. I’m happy for my genuine misclassifications to be cancelled out by others, but in these cases where I realise my error, I’m certain I could do something more helpful than just cancel out someone else’s correct answer.

**Comment by zarino** [comment]
Another request for Undo, from a Twitter user:

[![I think you need an undo button there! I made a couple of mistakes!](https://cloud.githubusercontent.com/assets/739624/9220052/8c9a145c-40d7-11e5-95f9-1c3032765963.png)](https://twitter.com/federicacocco/status/631176859590488064)

**Comment by MyfanwyNixon** [comment]
Definitely the most asked-for feature!

**Comment by zarino** [comment]
I feel like adding an Undo button that, when you click it, just says "Sorry, no takesies backsies. Be more careful next time." &lt;/grump&gt;

**Comment by andylolz** [comment]
Haha, I’m pleased my favourite made it into that screenshot :)
