### ISSUE TITLE
Only offer people for whom we don't yet have enough votes

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/gender-balance#306]
Rather than leaving all data always open for vote, switch the focus to be a drive for 'completion' — where everyone has had sufficient votes, and there's nothing more to do (until we get new people).

**Comment by chrismytton** [comment]
Currently when you go to the list of countries you just see the name of the country and *your* progress on it.

![screen shot 2016-01-12 at 16 49 13](https://cloud.githubusercontent.com/assets/22996/12270118/7318be28-b94c-11e5-80fe-7359f4f5e711.png)

Having discussed this with @tmtmtmtm we've decided that it would be good to expand this to include the current counts and % for the people we've already got sufficient votes for. If there are outstanding people that still need more votes then they get grouped into a separate **Unknown** section which includes the current progress bar.

Here is a rough design that @tmtmtmtm *literally* did on the back of a napkin.

![img_3702](https://cloud.githubusercontent.com/assets/22996/12270095/55b959dc-b94c-11e5-8470-cac43b0b7c3b.JPG)

**Comment by wfdd** [comment]
That's a good idea.

- How's the cut-off point gonna be calculated?
- How about there also remaining the option to play the full game, but bumping
  the people we've not got enough votes for to the front?  (I suppose, for some,
  it might be another way to be reminded of who their MPs are and would wanna
  flip through the lot of them.)  Is there a reason why we might wanna take the
  rest of the people out of the game?  I see there's actually two 'play'
  buttons, so it could be I've misunderstood.

**Comment by zarino** [comment]
Regarding the display of countries, is there a particular reason for displaying the figures, rather than, say, just using the gendered progress bar we use in-game?

![screen shot 2016-02-05 at 14 20 26](https://cloud.githubusercontent.com/assets/739624/12848776/c61480f6-cc13-11e5-9959-ab8660461719.png)

**Comment by zarino** [comment]
Notes from talking to @chrismytton:

* We want to change from making people play the entire legislature, to just playing people we don't yet have confirmed stats for.
* Thus, when you pick a country to play, you will often only be playing a fraction of the full legislature. Or it might happen that you can't play a country at all, because all of the politicians have already been completed.
* So when you're voting, you're only voting on the "undecided" ("unconfirmed?") fraction of the legislature. Which is why @tmtmtmtm suggested maybe putting the progress bar inside that – below the total number of unconfirmed politicians.
* The country cards, then, will end up showing the global status of the country (ie: "35 females, 83 males") and your personal status (ie: "you haven't made any votes yet" or "you have voted on 60% of people") – potential for confusion.
* We had a quick discussion over whether we even need to show the user's progress through a legislature – if the progress bar only shows *your* progress (rather than the "global" progress), then it's only really useful if you half-finish a legislature, and want to know how far you got before picking it back up.

**Comment by zarino** [comment]
A few quick ideas.

I started quite close to @tmtmtmtm’s original sketch, although, to keep things legible, the number of "unknown" people is hidden – all that's important is how many are left to play (because if the number’s 400, you're less likely to start it in your coffee break!)

![u_mwcxtpmvrc7xv9wndfe5ct3dmzk8dbsmfotsfgbm_6qi-i](https://cloud.githubusercontent.com/assets/739624/12885548/c1893ffc-ce5e-11e5-8f76-0743c92052bf.jpg)

Then on to a more minimal alternative, closer to what we currently have. Two progress bars, one for the global split, and one for your personal progress through the "new" politicians. It's fine if people don't realise that’s what it all means, because even just scrolling past they'll get a feel for how male or female a legislature is just by the top bar.

![we_ard7bvl4ymmrseirsbxne8nkkangh64oecnlfiutd3sbl](https://cloud.githubusercontent.com/assets/739624/12885583/f0f24a72-ce5e-11e5-86f1-08b61828025e.jpg)

We could potentially explain the second progress bar a bit better by making it look more like the in-game progress bar (ie: with a gender split, plus empty space on the right):

![933ua_qphcldukntoqf3k-sz3xwgd0poaiks5fuzubzfddoi](https://cloud.githubusercontent.com/assets/739624/12885810/c46531ca-ce60-11e5-9cb1-d8c8ca213388.jpg)

At least then, when you click it, you'll see an exactly identical progress bar on the game screen, and you'll realise they're the same thing.

But then it does start looking a lot like the top bar, so maybe that would need to look different somehow. Bit worried it all starts getting a bit confusing here, once we start adding in more styles and headings just to explain why there are two bars.

Hmm. Will think more over tea.

**Comment by tmtmtmtm** [comment]
The two primary requirements on this page are to (a) show if there are 'unknowns' for a country, thus inviting them to play and (b) show the breakdown for the 'knowns'. I don't think it's _necessary_ to also show a user's progress at this point — especially if that's likely to be confusing. The main thing we might want to be able to convey here is that even if _you_ have voted on 100% of the people, that's not the same as us having sufficient data on all of them (unless we effectively want to combine the two and simply report as if the user's votes are all definitely correct)

It's also worth noting that the most common case, for the majority of users, is that they won't have played most of the countries yet at all, so I'd be wary of optimising for the much less common case where they have.

**Comment by zarino** [comment]
In that case, we could take the second screenshot, and just drop the second progress bar. We don't display the user's past votes, just the number of people they have yet to play:

![frlgomnqwmr3xo8smvkccpdf7qyzrholeqoeef7npic71az6](https://cloud.githubusercontent.com/assets/739624/12892818/d019402c-ce85-11e5-8138-2a6b65ef6d7c.jpg)

The only thing that would change as you complete countries, would be the "You have `##` left to play" figure. Then, once you've completed a country, I guess it would say:

![bsdjxuqh15xffjqfvtquckn2sscmlsr5tko--odujswbq56w](https://cloud.githubusercontent.com/assets/739624/12892914/43f2bb9a-ce86-11e5-9f4e-f160d8d3b05e.jpg)

Maybe with a little reprise of the level completion trophy, or similar, to make completing a country look like an achievement.

**Comment by tmtmtmtm** [comment]
I think the main thing I'm worried about with that is that people might be confused as they see the 'to play' number going down, but the 'results' numbers not going up. 

In the case where we don't have any 'global' results for a country yet, that would mean ending up with "0 men | 0 women | ✓ Completed!" which seems a little odd.

**Comment by zarino** [comment]
(For the record, since this was discussed mostly in IRC:)

> In the case where we don't have any 'global' results for a country yet…

Looks like that's actually about 40% of countries right now. So the list should deffo make it clear what's going on in the case that the "global" progress bar is empty.

**Comment by zarino** [comment]
> The two primary requirements on this page are to (a) … and (b) show the breakdown for the 'knowns'.

@tmtmtmtm: Do you want to show the breakdown so that the page can function as a read-only "results" page in addition to a "pick a country to play" page? Or do you think that showing a country's current breakdown will influence a player's decision to contribute more to a country?

**Comment by zarino** [comment]
Okay, @tmtmtmtm @chrismytton – thoughts?

![known-bar-simplified](https://cloud.githubusercontent.com/assets/739624/12921803/c4ee55fe-cf46-11e5-8c74-328328bbf642.png)

- [x] Requirement 1: Show the "unknowns" (ie: people you can play) for a country.
- [x] Requirement 2: Show the breakdown for the remaining people.

More detail:

* We're combining what might typically be two pages (ie: a page showing you levels of a game that you can play, and another showing the output of the game globally) onto a single page, so I've tried to keep it as simple as possible.
* Country name is important, so it stays in the top left.
* Encouraging play is next most important, so that goes in the top right, and including the number of politicians left to play will subtly nudge people towards finishing off countries with the least work left to do (which is what we want!).
* Progress bar shows global progress towards the "known gender balance" of a country. Men and Women figures are displayed numerically as well as visually.
* We don't even attempt to explain the potential discrepancy between the number of votes a person has cast versus the number of "unknown" people in the progress bar (ie: from EveryPolitician). It's far too complex a subject to explain in such a small space.
* If you've cast any votes towards a country, the call-to-action says "X politician *left* to play", whereas, if you've not played a country before, it misses out the "left" (because you've not started yet!).
* Completed countries aren't clickable – the text is grey rather than blue and the drop shadow is replaces with a plain border, to make the card look less manipulable. The call-to-action is replaced with a forbidding-looking "You can't play this" message.
* Countries that *you* have completed show a little trophy, to reinforce the idea of achievement that you got immediately before, with the big shiny trophy in the game itself.

(I'm not sure how you'll want to define "countries I have completed" – I was thinking any country that you have "finished"—ie: swiped or clicked the final card, in game—at least once.)

If we want to further encourage completion of countries that require very few additional votes, then we could list them separately at the top of the page. A bit like the "featured country" you used to have, except a handful of countries, under an "Almost complete" heading, or somesuch.

**Comment by tmtmtmtm** [comment]
@zarino This is superb. I think this gets across all the different scenarios very cleanly and elegantly. For something so complex, this is pretty much perfect!

**Comment by chrismytton** [comment]
@zarino I agree with @tmtmtmtm, this looks perfect! :+1:
