### ISSUE TITLE
Explain the value of dis-aggregated data

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/gender-balance#325]
On http://www.gender-balance.org/about we currently note a few ways in which our data can be better than that from the IPU:

![screen shot 2016-03-21 at 20 55 29](https://cloud.githubusercontent.com/assets/57483/13933905/4c0143c8-efa7-11e5-8628-5fa226693450.png)

However, this doesn't note the most important distinction, which is that they provide only *aggregate* data — i.e. nothing more than a total for each legislature. This means it's not possible to do any other cross-filtering of that data — e.g. to see the breakdown by party, or by age range — never mind deeper analysis against attendance records, voting patterns, etc.

**Comment by tmtmtmtm** [comment]
@MyfanwyNixon you want to try add something along those lines?

**Comment by MyfanwyNixon** [comment]
-  Which country has the highest proportion of women in parliament?
-     Do women vote differently on issues like defence, the environment, or maternity benefits?
-     Exactly when did women come into power in different countries, and did their presence change the way the country was run?

Frustratingly, it’s difficult to provide an answer for these questions, because the objective data just isn’t there.

The closest thing is data from the [Inter-Parliamentary Union](http://www.ipu.org/iss-e/women.htm), but that can't be used for this kind of in-depth anaylsis. They simply provide a total for each legislature, rather than configurable data on individual politicians -- plus the figures are self-reported, often out of date, and only cover member countries.

For advanced insights, you need rich data that can be sliced in multiple ways. So, alongside politicians' gender, you might also compare by age, or party, or voting records, or by many other exciting factors.

All of which goes some way to explain why we created Gender Balance, an easy game that crowd-sources gender data across every parliament in the world.

And it's not just a one-off job. Gender Balance will continue to collect data as elections take place and administrations change, so it's always relevant.


## What will happen to the results?

As Gender Balance gathers that gender data, it's all fed back into [EveryPolitician](http://everypolitician.org/), our open data store for information on every legislature in the world. From there it can be downloaded and used by anyone wanting to find answers to those in-depth questions.

We hope that they will be useful for researchers, campaigners, politicians, sociologists… and you!

**Comment by tmtmtmtm** [comment]
@MyfanwyNixon that's excellent, thanks!  I'm not entirely sure what "configurable" data means there, though. I've just dropped that for now, but happy to put something back in if we can find the right word.
