### ISSUE TITLE
Analytics tracking

### ISSUE THREAD

**Issue by zarino** [everypolitician/gender-balance#93]
Things we should track:

* Pageviews
* Clicks on male/female/other/skip buttons
* Left/right swipes on jtinder cards
* "Google them!" clicks

**Comment by tmtmtmtm** [comment]
If @jacksonj04 could point us in the right direction for _how_ to add these, I'm happy to actually implement it.

**Comment by jacksonj04** [comment]
Page views are automatically tracked simply by including the GA tracking code you get when you create a new property - ping me if you have difficulty.

For everything else, you probably want to do it with [GA event tracking](https://developers.google.com/analytics/devguides/collection/analyticsjs/events), which is just a JavaScript function call. That is of course assuming you just want to record the fact that a left/right swipe happened, not any additional payload. I'm guessing all you could really want to know will be recorded in the app proper, so that won't be an issue though.

**Comment by zarino** [comment]
@tmtmtmtm – if you want to do this yourself, just adding the basic page tracking would probably get us 90% of the way there, then I can add event tracking at a later date.

**Comment by chrismytton** [comment]
Fixed in https://github.com/everypolitician/gender-balance/pull/178
